default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: blog_api_development

test:
  <<: *default
  database: blog_api_test

production:
  <<: *default
  database: blog_api_production